name: Terraform GCP VM Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform-dev:
    name: Recreate DEV
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Terraform

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

      - name: Terraform Init
        run: terraform init

      - name: Select DEV Workspace
        run: terraform workspace select dev || terraform workspace new dev

      - name: Terraform Destroy DEV (ignore if nothing exists)
        run: terraform destroy -auto-approve || true

      - name: Terraform Apply DEV
        run: terraform apply -auto-approve


  terraform-prod:
    name: Recreate PROD
    needs: terraform-dev
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Terraform

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

      - name: Terraform Init
        run: terraform init

      - name: Select PROD Workspace
        run: terraform workspace select prod || terraform workspace new prod

      - name: Terraform Destroy PROD (ignore if nothing exists)
        run: terraform destroy -auto-approve || true

      - name: Terraform Apply PROD
        run: terraform apply -auto-approve
